//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenergyApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionObject
    {
        public int IdWriting { get; set; }
        public Nullable<int> idStation { get; set; }
        public Nullable<int> idObject { get; set; }
        public Nullable<decimal> Condition { get; set; }
    }
}
