//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenergyApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        public int ObjectID { get; set; }
        public string NameObject { get; set; }
        public string NameStation { get; set; }
    }
}
