//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenergyApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectType
    {
        public int IdType { get; set; }
        public string TypeName { get; set; }
        public string FaseAmount { get; set; }
    }
}
